// <auto-generated />
using HealthEquityMembers.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HealthEquityMembers.Migrations
{
    [DbContext(typeof(MemberContext))]
    partial class MemberContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HealthEquityMembers.Models.Member", b =>
                {
                    b.Property<long>("MemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MemberId");

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            MemberId = 1L,
                            Email = "jeremytru91@gmail.com",
                            FirstName = "Jeremy",
                            LastName = "Trujillo",
                            PhoneNumber = "801-882-1432"
                        },
                        new
                        {
                            MemberId = 2L,
                            Email = "bob_someone@gmail.com",
                            FirstName = "Bob",
                            LastName = "Someone",
                            PhoneNumber = "801-111-1111"
                        },
                        new
                        {
                            MemberId = 3L,
                            Email = "jane_doe@gmail.com",
                            FirstName = "jane",
                            LastName = "doe",
                            PhoneNumber = "801-222-2222"
                        },
                        new
                        {
                            MemberId = 4L,
                            Email = "test_user@gmail.com",
                            FirstName = "test",
                            LastName = "user",
                            PhoneNumber = "801-333-3333"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
